### ISSUE TITLE
ETV eating up all swap & RAM in about 24 hours

### ISSUE THREAD

**Issue by Moonbase59** [ErsatzTV/ErsatzTV#1461]
I run ETV in an Ubuntu 22.04 LXC on a Proxmox machine, the same LXC I use for my Jellyfin server and which ran happily for weeks with 2 CPUs, 2 GB RAM and nearly zero swap.

Now I thought I’d give it a little more room for ETV and increased to 4 CPUs and 4 GB RAM. When running ETV, swap gets filled and sticks at 100% rather fast, and within ~24 hours all available RAM gets used. I increased again to 6 CPUs and 6 GB RAM, which are now after almost a day also used up.

![Auswahl_275](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/79435e42-e85a-4f1c-a140-c465b2d8e497)

Health Check:

![Auswahl_276](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/0171489c-4b21-493c-988d-df5ae0e953b0)

I suspect some memory leak, since the container ran just fine with Jellyfin over weeks (and with only 2 CPUs and 2 GB RAM).

If it helps, I had the Jellyfin AndroidTV client running for a few hours on my TV. Now I have disconnected all streaming clients and the RAM usage has dropped by ~1 GB, CPUs from 16% to 0.04%. I’ll leave it like this for a few more hours and see if it also increases when no clients are streaming. (The stream for the last 3 hours was a flooding 30s fallback video loop with a 80% size and 70% opacity watermark on it.)

![Kein Programm – Mozilla Firefox_001](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/d702166e-afa3-4e72-bc05-517dbe01cdc4)

**Any way I can help diagnosing this and get back to normal?** I mean, a media and TV server should be able to run for years, or—considering updates—at least months without bringing the server to a halt after only a day…

ETV is 0.8.2-beta-docker-vaapi and runs fine except the memory and swap issue.

I use this `docker-compose.yml`:

```yaml
version: '3'
services:
  app:
    image: 'jasongdove/ersatztv:latest-vaapi'
    restart: unless-stopped
    ports:
      - '8409:8409'
    environment:
      TZ: 'Europe/Berlin'
      'Bugsnag:Enable': 'false'
    devices:
      - '/dev/dri/card0:/dev/dri/card0'
      - '/dev/dri/renderD128:/dev/dri/renderD128'
    volumes:
      - ./config:/root/.local/share/ersatztv
      - /mnt/media/Videos/Elements:/mnt/media/Videos/Elements
```

**Comment by Moonbase59** [comment]
Some more info in case it turns out being relevant:

Machine: HP Z230 Workstation
CPU: 8 x Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (1 Socket)

```
$ vainfo
error: can't connect to X server!
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_14
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```

(Of course it can't find an X server on a headless system. But it looks like I could use i965 instead of the default driver. [Capabilities](https://www.intel.com/content/www/us/en/developer/articles/technical/linuxmedia-vaapi.html).)

**Comment by jasongdove** [comment]
Selecting the appropriate driver for hardware acceleration is a good first step! Some other changes I would recommend:

- Use a tmpfs (ram disk) mount for the transcode folder
- Use docker to enforce a memory limit on ETV. I use 4G but you can certainly experiment with lower values.

```yml
    tmpfs:
      - /root/.local/share/etv-transcode
    deploy:
      resources:
        limits:
          memory: 4G
```

`Thread Count` should be overridden by ETV back down to `1` when hardware acceleration is used, since many of those components don't support threading, but it wouldn't hurt to set to `1` in the ffmpeg profile.

I would also watch for source content that is encoded with HEVC/H265 since your GPU does not support decoding that content, it will always be done in software/CPU. It also doesn't support encoding HEVC, so it's a good decision to leave the video format in the ffmpeg profile set to `h264`.

**Comment by Moonbase59** [comment]
@jasongdove Thanks for coming back on this!

- `tmpfs`: I’m not too much into Docker (yet), what does the path specify? A folder in the host? Where else would I need to set things?
- Mem limit sounds like a good idea, didn’t know how to do that. Assuming my currently 6 GB, and leaving some room for Jellyfin, would you think 3 GB ok? (The actual hardware only has 32 GB, and there are some resource-hungry VMs running already.)
- ffmpeg thread count: It originally was set to `0` and (before using VAAPI) it ate all my CPUs, so I wanted to play safe. I can confirm that it now always only uses 1 thread (when using VAAPI). If it doesn’t block other things, I’ll set it to `1` now.
- H265: Yep, unfortunately the hardware can’t do that. Would be nice to save bandwith but I opted for H264 since it’s _much_ faster. Fortunately, this was also a decision I made some time ago for my sources, so _most_ of them are actually H264. Nevertheless, I _do_ have a few that are in H265. As I understand it, decoding should still be… well, _okay_…, and I’m _encoding_ to H264 anyway.

Could we agree that you check for any possible mem leaks, and I set ffmpeg threads to 1, add the docker mem limit and tmpfs and come back with testing results here?

I started a playout again after changing to the i965 driver (so ETV will actually do something), and already see mem usage slowly increasing again (swap full). Love the heavily decreased CPU load!

**Comment by jasongdove** [comment]
The tmpfs path is within the container and where etv already (temporarily) places transcoding output. No other configuration beyond what I pasted is needed.

**Comment by Moonbase59** [comment]
Cool, thanks! (I read it up in the Docker docs in the meantime.)

My current `docker-compose.yml` now looks like this:

```yaml
version: '3'
services:
  app:
    image: 'jasongdove/ersatztv:latest-vaapi'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 3G
    tmpfs:
      - /root/.local/share/etv-transcode
    ports:
      - '8409:8409'
    environment:
      TZ: 'Europe/Berlin'
      'Bugsnag:Enable': 'false'
    devices:
      - '/dev/dri/card0:/dev/dri/card0'
      - '/dev/dri/renderD128:/dev/dri/renderD128'
    volumes:
      - ./config:/root/.local/share/ersatztv
      - /mnt/media/Videos/Elements:/mnt/media/Videos/Elements
```

(Let me know if enabling the Bugsnag makes any sense for debugging this. I’m not against it, just think I’d like to enable it only if problems occur.)

The immediate result looks promising but I’ll keep watching it:

![Auswahl_277](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/8de520c1-28ce-4850-b594-fa5970f7d41d)

This is transcoding one stream with the settings I mentioned, and Jellyfin running in the same LXC, streaming to my browser, and _also_ transcoding _again_ using the same VAAPI.

![Kein Programm – Mozilla Firefox_002](https://github.com/ErsatzTV/ErsatzTV/assets/3706922/c7d03a0e-ad42-4442-8be9-70a553a550a7)
