### ISSUE TITLE
Feat Request: Play a random number of videos before playing filler - Music Videos

### ISSUE THREAD

**Issue by kulps** [ErsatzTV/ErsatzTV#1995]
This is a bit of a niche request, but I've setup a music video station and what I'd like is for the filler to play every 2-4 music videos. There was a similar but different request about setting the number of filler videos to play (https://github.com/ErsatzTV/ErsatzTV/issues/1871) but this is for playing a certain number of "main content" videos before playing the filler. It can be a bit much to have Video --> Filler --> Video --> Filler --> Video when the music videos are sometimes as short as 2.5 minutes. 

Ideally it would work similarly to the random function of the filler where you set the random count and any number of videos up to the set number will play before playing filler (Which also might have a random qty) 

Video qty: Random-4 
Filler qty: Random-2

e.g. 
Video --> Video --> Video --> Filler --> Video --> Video --> Filler --> Filler --> Video --> Filler --> Video --> Video --> Video --> Video --> Filler --> Video 

Or something similar. 

Thanks!

**Comment by jasongdove** [comment]
This can now be done using YAML playouts, which support scheduling a random number of items. This was added to the develop builds with https://github.com/ErsatzTV/ErsatzTV/pull/2102 and can be downloaded here https://github.com/ErsatzTV/ErsatzTV/releases/tag/develop

From the release notes:

```md
- YAML playout: make `count` an expression
    - The following parameters can be used:
        - `count`: the total number of items in the content
        - `random`: a random number between zero and (count - 1)
    - For example:
        - `count / 2` will play half of the items in the content
        - `random % 4 + 1` will play between 1 and 4 items
        - `2` (similar to before this change) will play exactly two items
```

and an example YAML playout that plays one filler between every 2 to 4 music videos:

```yaml
content:
  - search:
    key: "VIDEOS"
    query: "type:music_video"
    order: "shuffle"

  - search:
    key: "FILLER"
    query: "type:other_video AND tag:filler"
    order: "shuffle"

playout:
  - count: random % 3 + 2
    content: "VIDEOS"

  - count: 1
    content: "FILLER"
    filler_kind: postroll

  - repeat: true
```

Note that for a random range between `min` and `max` it should be `random % (max - min + 1) + min`.
