### ISSUE TITLE
Hardware transcoding error with AMD iGPU

### ISSUE THREAD

**Issue by irfanhakim-as** [ErsatzTV/ErsatzTV#1997]
I have ErsatzTV running in a Docker container, on a Proxmox LXC container, with device passthrough of my AMD Ryzen 5 5600G's iGPU for hardware transcoding (VAAPI). I've configured ErsatzTV to use my Jellyfin server as the media source, and my primary method of streaming my channels is also through said Jellyfin server/clients.

I've seen this error multiple times on ErsatzTV, from time to time, when attempting to stream a channel of mine:

```
HLS process for channel 101 has terminated unsuccessfully with exit code 137: amdgpu: os_same_file_description couldn't determine if two DRM fds reference the same file description.
```

Is this error obvious to anyone on what might be causing it? Often when this happens, if I'm observing correctly, by the time my playout has gone to the next media in the schedule, they'd play just fine. Initially I thought this might be an issue with said media file, but by the next time it cycles back to the _problematic_ media/show, it'd play that show just fine.

I've seen this happen on my Jellyfin server but only once, and I think that was due to a configuration error at the time with the source of my media library (can't tell for sure, I was in the middle of migrating my server at the time). On ETV though, it's happened multiple times already and it'd be great if I could know what's causing it and see if I could figure out a solution. Thanks!

---

Docker compose manifest:

```yaml
services:
  ersatztv:
    image: docker.io/jasongdove/ersatztv:v25.1.0-vaapi
    container_name: ersatztv-1
    group_add:
      - '104' # This needs to be the group id of running `stat -c '%g' /dev/dri/renderD128` on the docker host
    ports:
      - 8409:8409
    volumes:
      - /home/myuser/.local/share/ersatztv/config:/config
    #tmpfs:
    #  - /transcode
    devices:
      - /dev/dri:/dev/dri
      #- /dev/dri/renderD128:/dev/dri/renderD128
      #- /dev/dri/card0:/dev/dri/card0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
```

Troubleshooting > General information:

```json
{
  "Version": "25.1.0-docker-vaapi",
  "Health": [],
  "FFmpegSettings": {
    "FFmpegPath": "/usr/local/bin/ffmpeg",
    "FFprobePath": "/usr/local/bin/ffprobe",
    "DefaultFFmpegProfileId": 1,
    "PreferredAudioLanguageCode": "eng",
    "UseEmbeddedSubtitles": true,
    "ExtractEmbeddedSubtitles": false,
    "SaveReports": false,
    "GlobalWatermarkId": 1,
    "HlsSegmenterIdleTimeout": 60,
    "WorkAheadSegmenterLimit": 1,
    "InitialSegmentCount": 1,
    "HlsDirectOutputFormat": "MpegTs"
  },
  "Channels": [
    {
      "Id": 3,
      "UniqueId": "xxx",
      "Number": "101",
      "Name": "Ghibli",
      "Group": "ErsatzTV",
      "FFmpegProfileId": 3,
      "WatermarkId": 1,
      "StreamingMode": "HttpLiveStreamingSegmenterV2",
      "PreferredAudioLanguageCode": "jpn",
      "SubtitleMode": "Any",
      "MusicVideoCreditsMode": "None",
      "SongVideoMode": "Default",
      "ProgressMode": "Always",
      "WebEncodedName": "Ghibli"
    }
  ],
  "FFmpegProfiles": [
    {
      "Id": 3,
      "Name": "1080p HWT",
      "ThreadCount": 0,
      "HardwareAcceleration": "Vaapi",
      "VaapiDisplay": "drm",
      "VaapiDriver": "Default",
      "VaapiDevice": "/dev/dri/renderD128",
      "QsvExtraHardwareFrames": 64,
      "ResolutionId": 3,
      "Resolution": {
        "Id": 3,
        "Name": "1920x1080",
        "IsCustom": false,
        "Height": 1080,
        "Width": 1920
      },
      "ScalingBehavior": "ScaleAndPad",
      "VideoFormat": "Hevc",
      "VideoProfile": "high",
      "VideoPreset": "",
      "AllowBFrames": false,
      "BitDepth": "EightBit",
      "VideoBitrate": 4000,
      "VideoBufferSize": 8000,
      "AudioFormat": "Aac",
      "AudioBitrate": 192,
      "AudioBufferSize": 384,
      "NormalizeLoudnessMode": "Off",
      "AudioChannels": 2,
      "AudioSampleRate": 48,
      "NormalizeFramerate": false,
      "DeinterlaceVideo": true
    }
  ]
}
```

Please let me know if there are any more information you might need!
