### ISSUE TITLE
Can't see sidebar submenus in new release 25.2.0

### ISSUE THREAD

**Issue by oliverm91** [ErsatzTV/ErsatzTV#2068]
I just upgraded to 25.2.0 (came from 25.1.0 ersatztv-vaapi) and I noticed that I can't open submenus in the sidebar. The only submenu I see is Support that comes open by default. I can close it, but can't reopen. The little arrows do spin and turn green but nothing shows. Already tried restarting the docker.

System:

- OS: TrueNAS Community 25.04.1
- CPU: Intel 12100
- RAM: 16 GB RAM
- No GPU

YAML install

```
services:
  ersatztv:
    container_name: ersatztv
    devices:
      - /dev/dri:/dev/dri
    environment:
      - TZ=America/Santiago
    image: jasongdove/ersatztv:latest
    ports:
      - '8409:8409'
    restart: unless-stopped
    volumes:
      - /mnt/tank/library:/media:ro
      - /mnt/apps/apps_config/ersatztv_config:/config
      - /mnt/apps/apps_config/ersatztv_transcode:/transcode
version: '3.8'
```

![Image](https://github.com/user-attachments/assets/5cae4172-2eae-4dbe-8040-71bdfb0fb919)
![Image](https://github.com/user-attachments/assets/b74f0cc9-414e-447f-9d31-961823e43139)
![Image](https://github.com/user-attachments/assets/fe6bb30b-674a-4dd7-9cba-ab06dce10c2a)
